/// Severity of a proactive alert
enum AlertSeverity {
  low,
  medium,
  high,
  critical,
}

/// Domain of the system affected
enum AlertDomain {
  hardware,
  code,
  security,
  mission,
}

/// Time horizon for predicted issues
enum AlertTimeHorizon {
  immediate,
  short,
  future,
}

/// A proactive alert intent generated by the Proactive Alert Engine (PAE).
class AlertIntent {
  final String id;
  final AlertSeverity severity;
  final AlertDomain domain;
  final AlertTimeHorizon horizon;
  final double confidence;
  final String description;
  final String? recommendedAction;
  final bool vocalizeCandidate;
  final Map<String, dynamic> metadata;

  AlertIntent({
    required this.id,
    required this.severity,
    required this.domain,
    required this.horizon,
    required this.confidence,
    required this.description,
    this.recommendedAction,
    this.vocalizeCandidate = false,
    this.metadata = const {},
  });

  bool get isHighRisk =>
      severity == AlertSeverity.high || severity == AlertSeverity.critical;
}

/// Chatter Profiles for JARVIS-style personality
enum ChatterProfile {
  silent, // No voice, ever
  tactical, // Only emergencies/critical
  assistive, // Helpful commentary
  cinematic, // Tony Stark banter
}
